name: ✨ 功能建议
description: 提出一个改进想法或新功能
title: "[Feature] "
labels: ["type/feature"]
body:
  - type: markdown
    attributes:
      value: |
        欢迎提建议！请尽量说明动机、期望效果与可选方案，方便讨论取舍。

  - type: textarea
    id: motivation
    attributes:
      label: 背景 / 动机
      description: 你遇到了什么问题？为什么需要这个功能？
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 方案描述
      description: 你希望怎么做？是否有 UI/交互或 API 设计的想法？
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 可选方案
      description: 有哪些替代方案？为什么不够好？
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: 补充信息
      description: 相关链接、截图、参考实现等
    validations:
      required: false

